#!/bin/bash

apk update

apk upgrade

cat <<EOF > docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
EOF

echo

# Esse while True serve para só progredir quando o usuário colocar o login dele corretamente, caso contrário, o script inteiro não irá rodar pela falta de dependências necessárias

# $? armazena o código de saída do último comando executado
# 0 indica que o comando foi bem-sucedido
# Qualquer valor diferente de 0 indica que houve um erro
# A comparação [-eq] verifica se $? "é igual a" 0
# Se for igual a 0, significa que o último comando executou com sucesso

# Ou seja, ele verifica se o último comando foi bem-sucedido (exit status 0)
while true; do
    docker login
    if [ $? -eq 0 ]; then
        break
    else
        echo
    fi
done

echo

docker-compose up -d

echo

pip install mysql-connector-python colorama tqdm

echo

cat <<EOF > progress_bar.py
import time
from tqdm import tqdm

total_time = 60
interval = 0.1

for _ in tqdm(range(int(total_time / interval)), desc="Iniciando o servidor MySQL", bar_format="{l_bar}{bar}"):
    time.sleep(interval)
EOF

python progress_bar.py

echo

echo "O servidor MySQL foi iniciado!"

echo

cat <<EOF > arquivo.py
import mysql.connector
from colorama import *

init()

mydb = mysql.connector.connect(
  host="localhost",
  user="myuser",
  password="mypassword",
  database="mydatabase"
)

mycursor = mydb.cursor()

mycursor.execute("""CREATE TABLE IF NOT EXISTS TB_ALUNOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome TEXT
);""")

mycursor.execute("""CREATE TABLE IF NOT EXISTS TB_PROFESSOR (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome TEXT
);""")

mycursor.execute("""CREATE TABLE IF NOT EXISTS TB_DISCIPLINA (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome TEXT
);""")

mycursor.execute("""CREATE TABLE IF NOT EXISTS Matricula (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_aluno INT,
    id_professor INT,
    id_disciplina INT,
    nota_N1 FLOAT,
    nota_N2 FLOAT,
    media FLOAT,
    faltas INT,
    Aprovado_SN BOOLEAN,
    FOREIGN KEY (id_aluno) REFERENCES TB_ALUNOS(id),
    FOREIGN KEY (id_professor) REFERENCES TB_PROFESSOR(id),
    FOREIGN KEY (id_disciplina) REFERENCES TB_DISCIPLINA(id)
);""")


mydb.commit()

# Funcionalidades CRUD para geral

# Create
def create_data_on_table(tabela):
    match(tabela):
        case "TB_ALUNOS":
            nome = input("Coloque o nome do aluno: ")
            mycursor.execute("INSERT INTO TB_ALUNOS (nome) VALUES (%s);", (nome,))
            mydb.commit()
        case "TB_PROFESSOR":
            nome = input("Coloque o nome do professor: ")
            mycursor.execute("INSERT INTO TB_PROFESSOR (nome) VALUES (%s);", (nome,))
            mydb.commit()
        case "TB_DISCIPLINA":
            nome = input("Coloque o nome da disciplina: ")
            mycursor.execute("INSERT INTO TB_DISCIPLINA (nome) VALUES (%s);", (nome,))
            mydb.commit()
        case "Matricula":
            nome_aluno = input("Coloque o ID do aluno: ")
            nome_professor = input("Coloque o ID do professor: ")
            disciplina = input("Coloque o ID da disciplina: ")
            nota_N1 = float(input("Coloque a nota da N1: "))
            nota_N2 = float(input("Coloque a nota da N2: "))
            faltas = int(input("Coloque o número de faltas: "))

            media_parcial = (2 * nota_N1 + 3 * nota_N2) / 5

            if media_parcial < 6.0 or faltas >= 20:
                aprovado_sn = False
            else:
                aprovado_sn = True

            mycursor.execute("INSERT INTO Matricula (id_aluno, id_professor, id_disciplina, nota_N1, nota_N2, media, faltas, Aprovado_SN) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);", (nome_aluno, nome_professor, disciplina, nota_N1, nota_N2, media_parcial, faltas, aprovado_sn))
            mydb.commit()

# Read
def read_data_on_table(tabela):
    mycursor.execute(f"SELECT * FROM {tabela}")
    meuresultado = mycursor.fetchall()

    match(tabela):
        case "TB_ALUNOS":
            for item in meuresultado:
                id, nome = item
                print(f"ID: {id}, ",
                    f"Aluno: {nome}")
        case "TB_PROFESSOR":
            for item in meuresultado:
                id, nome = item
                print(f"ID: {id}, ",
                    f"Professor: {nome}")
        case "TB_DISCIPLINA":
            for item in meuresultado:
                id, nome = item
                print(f"ID: {id}, ",
                    f"Disciplina: {nome}")
        case "Matricula":
            for item in meuresultado:
                id, id_aluno, id_professor, disciplina, nota_N1, nota_N2, media, faltas, aprovado_sn = item

                mycursor.execute(f"SELECT nome FROM TB_ALUNOS WHERE id = {id_aluno}")
                nome_aluno = mycursor.fetchone()[0]

                mycursor.execute(f"SELECT nome FROM TB_PROFESSOR WHERE id = {id_professor}")
                nome_professor = mycursor.fetchone()[0]

                mycursor.execute(f"SELECT nome FROM TB_DISCIPLINA WHERE id = {disciplina}")
                nome_disciplina = mycursor.fetchone()[0]

                if media < 6.0 or faltas >= 20:
                    aprovado_sn = False
                else:
                    aprovado_sn = True

                # Nome do status após ser aprovado
                if aprovado_sn:
                    status = "Aprovado por Média"
                elif (not aprovado_sn) and (faltas >= 20) and (media < 6.0):
                    status = "Reprovado por Falta e por Média"
                elif (not aprovado_sn) and (faltas >= 20):
                    status = "Reprovado por Falta"
                elif (not aprovado_sn) and (media < 6.0):
                    status = "Reprovado por Média"

                # Cor das Faltas
                if faltas < 10:
                    faltas_color = Fore.GREEN
                elif faltas < 20:
                    faltas_color = Fore.YELLOW
                else:
                    faltas_color = Fore.RED

                # Cor dos Status
                if aprovado_sn:
                    status_color = Fore.GREEN  
                else:
                    status_color = Fore.RED

                # Cor da Nota N1
                if nota_N1 <= 5:
                    nota_n1_color = Fore.RED
                elif nota_N1 <= 9:
                    nota_n1_color = Fore.YELLOW
                else:
                    nota_n1_color = Fore.GREEN

                # Cor da Nota N2
                if nota_N2 <= 5:
                    nota_n2_color = Fore.RED
                elif nota_N2 <= 9:
                    nota_n2_color = Fore.YELLOW
                else:
                    nota_n2_color = Fore.GREEN

                # Cor da media
                if media <= 5:
                    media_color = Fore.RED
                elif media <= 9:
                    media_color = Fore.YELLOW
                else:
                    media_color = Fore.GREEN

                # Cor da Disciplina
                match(nome_disciplina):
                    case "PHP":
                        disciplina_color = Fore.LIGHTBLUE_EX
                    case _:
                        disciplina_color = ""

                # Eu poderia colocar esses IFs acima como forma de ternário na parte onde tem as suas respectivas variáveis abaixo
                # Mas ternário em Python é muito feio e fica bem difícil de entender para onde cada coisa vai
                # Exemplo: f"Faltas:{Fore.GREEN if faltas < 10 else Fore.YELLOW if faltas <= 20 else Fore.RED} {faltas} {Fore.RESET}"
                print(f"ID: {id}, "
                    f"Aluno: {nome_aluno}, "
                    f"Professor: {nome_professor}, "
                    f"Disciplina:{disciplina_color} {nome_disciplina}{Fore.RESET}, "
                    f"Nota N1:{nota_n1_color} {nota_N1}{Fore.RESET}, "
                    f"Nota N2:{nota_n2_color} {nota_N2}{Fore.RESET}, "
                    f"Media:{media_color} {media}{Fore.RESET}, "
                    f"Faltas:{faltas_color} {faltas}{Fore.RESET}, "
                    f"Status:{status_color} {status}{Style.RESET_ALL}")

# Update
def update_data_on_table(tabela):
    id = int(input("Qual o id da linha que você deseja atualizar: "))
    match(tabela):
        case "TB_ALUNOS":
            nome = input("Coloque o nome do aluno: ")
            mycursor.execute(f"UPDATE TB_ALUNOS SET nome = %s WHERE id = %s;", (nome, id))
            mydb.commit()
        case "TB_PROFESSOR":
            nome = input("Coloque o nome do professor: ")
            mycursor.execute(f"UPDATE TB_PROFESSOR SET nome = %s WHERE id = %s;", (nome, id))
            mydb.commit()
        case "TB_DISCIPLINA":
            nome = input("Coloque o nome da disciplina: ")
            mycursor.execute(f"UPDATE TB_DISCIPLINA SET nome = %s WHERE id = %s;", (nome, id))
            mydb.commit()
        case "Matricula":
            id_aluno = input("Coloque o ID do aluno: ")
            id_professor = input("Coloque o ID do professor: ")
            id_disciplina = input("Coloque o ID da disciplina: ")
            nota_N1 = float(input("Coloque a nota da N1: "))
            nota_N2 = float(input("Coloque a nota da N2: "))
            faltas = int(input("Coloque o número de faltas: "))

            media_parcial = (2 * nota_N1 + 3 * nota_N2) / 5

            if media_parcial < 6.0 or faltas >= 20:
                aprovado_sn = False
            else:
                aprovado_sn = True

            mycursor.execute(f"UPDATE Matricula SET id_aluno = %s, id_professor = %s, id_disciplina = %s, nota_N1 = %s, nota_N2 = %s, media = %s, faltas = %s, Aprovado_SN = %s WHERE id = %s;", (id_aluno, id_professor, id_disciplina, nota_N1, nota_N2, media_parcial, faltas, aprovado_sn, id))
            mydb.commit()

# Delete
def delete_data_on_table(tabela):
    id = int(input("Qual o id da linha que você deseja deletar: "))
    mycursor.execute(f"DELETE FROM {tabela} WHERE id = %s", (id,))
    mydb.commit()

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- #

# Input do usuário

while True:

    print("""1 - Colocar os dados manualmente no banco de dados
2 - Ver um preview do resultado final
3 - Listar todos os aluno aprovados
4 - Listar todos os alunos reprovados
5 - Listar a quantidade de alunos aprovados
6 - Listar a quantidade de alunos reprovados
7 - Sair
""")

    escolha_usuario = int(input("O que você deseja fazer? "))

    print()

    match(escolha_usuario):
        case 1:
            while True:
                print("Escolha uma função abaixo")

                print()

                print("""1 - Criar um dado novo em uma tabela (TB_ALUNOS, TB_PROFESSOR, TB_DISCIPLINA, Matricula)
2 - Ler todos os dados na tabela (TB_ALUNOS, TB_PROFESSOR, TB_DISCIPLINA, Matricula)
3 - Atualizar um dado na tabela (TB_ALUNOS, TB_PROFESSOR, TB_DISCIPLINA, Matricula)
4 - Deletar um dado na tabela (TB_ALUNOS, TB_PROFESSOR, TB_DISCIPLINA, Matricula)
5 - Sair
""")

                escolha = int(input("O que você deseja fazer? "))

                if escolha < 5:
                    while True:

                        print()

                        print("""Escolha uma tabela abaixo
1 - TB_ALUNOS
2 - TB_PROFESSOR
3 - TB_DISCIPLINA
4 - Matricula
""")

                        escolha_tabela = int(input("O que você deseja fazer? "))

                        if escolha_tabela > 4 or escolha_tabela < 1:
                            print("Escolha um número entre 1 e 4")
                            continue
                        else:
                            match(escolha_tabela):
                                case 1:
                                    nome_tabela = "TB_ALUNOS"
                                case 2:
                                    nome_tabela = "TB_PROFESSOR"
                                case 3:
                                    nome_tabela = "TB_DISCIPLINA"
                                case 4:
                                    nome_tabela = "Matricula"

                        print()   
                        break

                    match(escolha):
                        case 1:
                            create_data_on_table(nome_tabela)
                        case 2:
                            read_data_on_table(nome_tabela)
                        case 3:
                            update_data_on_table(nome_tabela)
                        case 4:
                            delete_data_on_table(nome_tabela)
                        case 5:
                            break

                    print()

                elif escolha > 5:
                    print("Escolha um número entre 1 e 5")
                    continue
                else:
                    break
        case 2:
            mycursor.execute("INSERT INTO TB_ALUNOS (nome) VALUES (%s);", ("Leandro",))
            mydb.commit()
            id_aluno = mycursor.lastrowid

            mycursor.execute("INSERT INTO TB_PROFESSOR (nome) VALUES (%s);", ("Anthony",))
            mydb.commit()
            id_professor = mycursor.lastrowid

            mycursor.execute("INSERT INTO TB_DISCIPLINA (nome) VALUES (%s);", ("PHP",))
            mydb.commit()
            id_disciplina = mycursor.lastrowid

            nota_N1 = 5.0
            nota_N2 = 7.0
            faltas = 9
            media_parcial = (2 * nota_N1 + 3 * nota_N2) / 5

            if media_parcial < 6.0 or faltas >= 20:
                aprovado_sn = False
            else:
                aprovado_sn = True

            mycursor.execute("INSERT INTO Matricula (id_aluno, id_professor, id_disciplina, nota_N1, nota_N2, media, faltas, Aprovado_SN) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);", (id_aluno, id_professor, id_disciplina, nota_N1, nota_N2, media_parcial, faltas, aprovado_sn))
            mydb.commit()
            id_matricula = mycursor.lastrowid

            read_data_on_table("Matricula")

            print()
            input("Pressione Enter para continuar")

            mycursor.execute("DELETE FROM Matricula WHERE id = %s", (id_matricula,))
            mydb.commit()

            mycursor.execute("DELETE FROM TB_ALUNOS WHERE id = %s", (id_aluno,))
            mydb.commit()

            mycursor.execute("DELETE FROM TB_PROFESSOR WHERE id = %s", (id_professor,))
            mydb.commit()

            mycursor.execute("DELETE FROM TB_DISCIPLINA WHERE id = %s", (id_disciplina,))
            mydb.commit()

            mycursor.execute("ALTER TABLE TB_ALUNOS AUTO_INCREMENT = 1")
            mydb.commit()

            mycursor.execute("ALTER TABLE TB_PROFESSOR AUTO_INCREMENT = 1")
            mydb.commit()

            mycursor.execute("ALTER TABLE TB_DISCIPLINA AUTO_INCREMENT = 1")
            mydb.commit()

            mycursor.execute("ALTER TABLE Matricula AUTO_INCREMENT = 1")
            mydb.commit()
        
        case 3: 
            mycursor.execute("SELECT * FROM Matricula WHERE Aprovado_sn = 1")
            meuresultado = mycursor.fetchall()

            if not meuresultado:
                print("Nenhum aluno foi aprovado.")
            else:
                for item in meuresultado:
                    id, id_aluno, id_professor, disciplina, nota_N1, nota_N2, media, faltas, aprovado_sn = item

                    mycursor.execute(f"SELECT nome FROM TB_ALUNOS WHERE id = {id_aluno}")
                    nome_aluno = mycursor.fetchone()[0]

                    mycursor.execute(f"SELECT nome FROM TB_PROFESSOR WHERE id = {id_professor}")
                    nome_professor = mycursor.fetchone()[0]

                    mycursor.execute(f"SELECT nome FROM TB_DISCIPLINA WHERE id = {disciplina}")
                    nome_disciplina = mycursor.fetchone()[0]

                    if aprovado_sn:
                        status = "Aprovado por Média"
                    elif (not aprovado_sn) and (faltas >= 20) and (media < 6.0):
                        status = "Reprovado por Falta e por Média"
                    elif (not aprovado_sn) and (faltas >= 20):
                        status = "Reprovado por Falta"
                    elif (not aprovado_sn) and (media < 6.0):
                        status = "Reprovado por Média"

                    # Cor das Faltas
                    if faltas < 10:
                        faltas_color = Fore.GREEN
                    elif faltas < 20:
                        faltas_color = Fore.YELLOW
                    else:
                        faltas_color = Fore.RED

                    # Cor dos Status
                    if aprovado_sn:
                        status_color = Fore.GREEN  
                    else:
                        status_color = Fore.RED

                    # Cor da Nota N1
                    if nota_N1 <= 5:
                        nota_n1_color = Fore.RED
                    elif nota_N1 <= 9:
                        nota_n1_color = Fore.YELLOW
                    else:
                        nota_n1_color = Fore.GREEN

                    # Cor da Nota N2
                    if nota_N2 <= 5:
                        nota_n2_color = Fore.RED
                    elif nota_N2 <= 9:
                        nota_n2_color = Fore.YELLOW
                    else:
                        nota_n2_color = Fore.GREEN

                    # Cor da media
                    if media <= 5:
                        media_color = Fore.RED
                    elif media <= 9:
                        media_color = Fore.YELLOW
                    else:
                        media_color = Fore.GREEN

                    # Cor da Disciplina
                    match(nome_disciplina):
                        case "PHP":
                            disciplina_color = Fore.LIGHTBLUE_EX
                        case _:
                            disciplina_color = ""
                            
                    print(f"ID: {id}, "
                        f"Aluno: {nome_aluno}, "
                        f"Professor: {nome_professor}, "
                        f"Disciplina:{disciplina_color} {nome_disciplina}{Fore.RESET}, "
                        f"Nota N1:{nota_n1_color} {nota_N1}{Fore.RESET}, "
                        f"Nota N2:{nota_n2_color} {nota_N2}{Fore.RESET}, "
                        f"Media:{media_color} {media}{Fore.RESET}, "
                        f"Faltas:{faltas_color} {faltas}{Fore.RESET}, "
                        f"Status:{status_color} {status}{Style.RESET_ALL}")

        case 4:
            mycursor.execute(f"SELECT * FROM Matricula WHERE Aprovado_sn = 0")
            meuresultado = mycursor.fetchall()

            if not meuresultado:
                print("Nenhum aluno foi reprovado.")
            else:
                for item in meuresultado:
                    id, id_aluno, id_professor, disciplina, nota_N1, nota_N2, media, faltas, aprovado_sn = item

                    mycursor.execute(f"SELECT nome FROM TB_ALUNOS WHERE id = {id_aluno}")
                    nome_aluno = mycursor.fetchone()[0]

                    mycursor.execute(f"SELECT nome FROM TB_PROFESSOR WHERE id = {id_professor}")
                    nome_professor = mycursor.fetchone()[0]

                    mycursor.execute(f"SELECT nome FROM TB_DISCIPLINA WHERE id = {disciplina}")
                    nome_disciplina = mycursor.fetchone()[0]

                    if aprovado_sn:
                        status = "Aprovado por Média"
                    elif (not aprovado_sn) and (faltas >= 20) and (media < 6.0):
                        status = "Reprovado por Falta e por Média"
                    elif (not aprovado_sn) and (faltas >= 20):
                        status = "Reprovado por Falta"
                    elif (not aprovado_sn) and (media < 6.0):
                        status = "Reprovado por Média"

                    # Cor das Faltas
                    if faltas < 10:
                        faltas_color = Fore.GREEN
                    elif faltas < 20:
                        faltas_color = Fore.YELLOW
                    else:
                        faltas_color = Fore.RED

                    # Cor dos Status
                    if aprovado_sn:
                        status_color = Fore.GREEN  
                    else:
                        status_color = Fore.RED

                    # Cor da Nota N1
                    if nota_N1 <= 5:
                        nota_n1_color = Fore.RED
                    elif nota_N1 <= 9:
                        nota_n1_color = Fore.YELLOW
                    else:
                        nota_n1_color = Fore.GREEN

                    # Cor da Nota N2
                    if nota_N2 <= 5:
                        nota_n2_color = Fore.RED
                    elif nota_N2 <= 9:
                        nota_n2_color = Fore.YELLOW
                    else:
                        nota_n2_color = Fore.GREEN

                    # Cor da media
                    if media <= 5:
                        media_color = Fore.RED
                    elif media <= 9:
                        media_color = Fore.YELLOW
                    else:
                        media_color = Fore.GREEN

                    # Cor da Disciplina
                    match(nome_disciplina):
                        case "PHP":
                            disciplina_color = Fore.LIGHTBLUE_EX
                        case _:
                            disciplina_color = ""
                            
                    print(f"ID: {id}, "
                        f"Aluno: {nome_aluno}, "
                        f"Professor: {nome_professor}, "
                        f"Disciplina:{disciplina_color} {nome_disciplina}{Fore.RESET}, "
                        f"Nota N1:{nota_n1_color} {nota_N1}{Fore.RESET}, "
                        f"Nota N2:{nota_n2_color} {nota_N2}{Fore.RESET}, "
                        f"Media:{media_color} {media}{Fore.RESET}, "
                        f"Faltas:{faltas_color} {faltas}{Fore.RESET}, "
                        f"Status:{status_color} {status}{Style.RESET_ALL}")

        case 5:
            mycursor.execute(f"SELECT * FROM Matricula WHERE Aprovado_sn = 1")
            meuresultado = mycursor.fetchall()

            n_aprovado = 0

            for item in meuresultado:
                n_aprovado += 1

            print("Número de aprovados: " + str(n_aprovado))

        case 6:
            mycursor.execute(f"SELECT * FROM Matricula WHERE Aprovado_sn = 0")
            meuresultado = mycursor.fetchall()

            n_reprovado = 0

            for item in meuresultado:
                n_reprovado += 1

            print("Número de reprovados: " + str(n_reprovado))

        case 7:
            break

    print()

mycursor.close()
mydb.close()
EOF

# Esse sleep é desnecessário e perde o tempo de todo mundo, mas eu achei interessante colocar para o usuário se preparar para vir uma porrada de informação do banco de dados de uma vez só
sleep 1

python arquivo.py